### ISSUE TITLE
Duplicate Tags cause crashes

### ISSUE THREAD

**Issue by codyswanner** [codyswanner/Meme-Cataloger2#10]
User is able to add duplicate tags to an image (which in itself is buggy behavior).  When trying to remove one of these duplicate tags, database query fails (expected one result, got more than one) and causes a minor crash.

Troubleshoot if there is a way to cause the database query to succeed even if duplicate records are returned, and then remove the user's ability to add a duplicate tag.  (Issue #2 may resolve the user ability to add duplicate tags by implementing Autocomplete component.)

**Comment by tycariadus** [comment]
I think I have experienced a similar issue.  I added a tag and each time I access the account that has the tag, or a report it causes the file to crash.  can you guys help me to remove / fix the issue?  Do you need the dmp file?  Thanks

**Comment by codyswanner** [comment]
Hello @tycariadus!  Based on your comment I'm thinking you may have ended up here by mistake, this repository is for an application that is not yet in production and is not accessible to the public.  What application was giving you an issue?

**Comment by tycariadus** [comment]
MoneyManager EX

**Comment by codyswanner** [comment]
Pull request #14 addresses this issue
